services:
  localstack:
    image: localstack/localstack-pro:4.11.1
    environment:
      - LOCALSTACK_AUTH_TOKEN=<PLEASE ADD YOUR TOKEN HERE>
      - LOCALSTACK_PERSISTENCE=1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"