services:
  localstack:
    image: localstack/localstack-pro:4.11.1
    environment:
      - LOCALSTACK_AUTH_TOKEN=<PLEASE ADD YOUR TOKEN HERE>
      - LOCALSTACK_PERSISTENCE=1
      - EXTERNAL_SERVICE_PORTS_START=4510
      - EXTERNAL_SERVICE_PORTS_END=4512
    ports:
      - "4566:4566"
      - "4511:4511"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"